/**
 * Danh sách icon Material Symbols được dùng trong app.
 *
 * Font icon đầy đủ nặng ~4MB nên chỉ tải đúng các glyph này qua tham số
 * `icon_names` của Google Fonts. Thêm icon mới thì phải khai báo ở đây,
 * nếu không glyph sẽ không được tải và trình duyệt hiện ra tên chữ.
 */
export const ICON_NAMES = [
  "account_balance",
  "account_balance_wallet",
  "add",
  "add_circle",
  "alarm",
  "analytics",
  "arrow_back",
  "arrow_downward",
  "arrow_drop_down",
  "arrow_forward",
  "arrow_upward",
  "auto_mode",
  "balance",
  "bar_chart",
  "bolt",
  "calendar_month",
  "campaign",
  "category",
  "check",
  "check_box",
  "check_circle",
  "chevron_left",
  "chevron_right",
  "close",
  "cloud_upload",
  "computer",
  "content_copy",
  "credit_card",
  "dark_mode",
  "dashboard",
  "dataset",
  "delete",
  "description",
  "done_all",
  "download",
  "edit",
  "equalizer",
  "error",
  "file_upload",
  "event",
  "expand_more",
  "file_download",
  "filter_list",
  "grid_view",
  "group",
  "groups",
  "hourglass_top",
  "info",
  "inventory_2",
  "light_mode",
  "menu",
  "more_horiz",
  "notification_important",
  "notifications_active",
  "payments",
  "percent",
  "person",
  "picture_as_pdf",
  "pie_chart",
  "pie_chart_outline",
  "priority_high",
  "psychology",
  "qr_code_2",
  "receipt",
  "receipt_long",
  "refresh",
  "savings",
  "schedule",
  "search",
  "send",
  "settings",
  "share",
  "smart_toy",
  "sort",
  "table_chart",
  "table_view",
  "task_alt",
  "tips_and_updates",
  "trending_flat",
  "trending_up",
  "tune",
  "undo",
  "upload_file",
  "verified",
  "warning",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/**
 * URL stylesheet Google Fonts đã subset đúng các icon ở trên.
 */
export const MATERIAL_SYMBOLS_HREF =
  "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" +
  `&icon_names=${[...ICON_NAMES].sort().join(",")}&display=block`;
